### PR TITLE
adds Makefile and updates the source geojson files

### PR DESCRIPTION
**Pull request by thecristen**
Not sure if this arrangement works (had some trouble running the app), but this might be useful.

### CODE REVIEW

**Comment by carpeliam** [comment]
oh wow, a pull request! so cool! awesome stuff. If the GeoJSON stuff has updates, I'd like to pull those in immediately, but I'm hesitant on the Makefile... I know this repo is built on an ages-old version of npm, but npm supports task running natively and it'd be nice to use the built-in stuff, which has one advantage over Make in being cross-platform-compatible. Completely open to discussion though.

@thecristen I'm moving back to Massachusetts as we speak (I'm in Utah right now, should be in Boston around Labor Day weekend) and I'll be at the first CfB event after that - any chance this can wait until then?

**Comment by thecristen** [comment]
Aha that's a great idea to perform the task with an npm script! Will look into that...

Definitely no rush on this. See you in a few weeks!

**Comment by thadk** [comment]
Hi Liam, If we wanted to port this, we could technically use [mapshaper](https://github.com/mbloch/mapshaper) into grunt/Javascript for the shp -> geojson conversion instead of ogr2ogr. 

That said, Makefiles are pretty convenient for generating data files. The data tools used can be more diverse than just javascript. We are talking about be adding a new voting polling place "Wait Time" indicator separate backend service. 
It may need input from processing the ward files somehow to generate QR codes.

**Comment by carpeliam** [comment]
Hey @thadk! (miss you guys!) To be honest I haven't actually looked at the tech for actually generating the geojson, but I'll be able to do that when I get back to Boston (less than a week!). With respect to Makefiles etc, mostly I'm interested in keeping the number of things a maintainer would have to install and interact with on their own machine to a minimum, to keep that barrier to entry low (this PR actually reminded me to open #24), but if there are ways to do that which are friendly to non-JS devs as well, so much the better.

**Comment by thecristen** [comment]
Since it looks like the files are updated so infrequently, I think it might be better to leave the updating process manual. Can always reopen this if we see a need.

**Pull request closed without merging**
