### PR TITLE
Display polling hours, status and any important information

### PR DESCRIPTION
**Pull request by moczka**
Added Google Now-like info card to display polling hours and status. The info card is displayed below the directions and only displays polling dates on or after the current date.

screen shot 2016-09-29 at 12 32 03 am

### CODE REVIEW

**Comment by moczka** [comment]
We will be over the UI design aspects with Christen and rearrange the module to meet the needs accordingly.

**Comment by thecristen** [comment]
Yeah once we get straightened out how to treat early locations vs 'normal' locations then we'll be able to move forward. Love the look and feel of this approach though 😍

**Comment by moczka** [comment]
So i will make changes to the module so it returns a table with all the hours through a method call after being fed the hours in an array. I will also remove it out into its own separate js file. The reason being that this could be used by any of the other collaborators.

**Comment by carpeliam** [comment]
It's actually kind of awesome that we have 3 PRs all for early voting. I'll work on pulling work from each of them in, and then close them each afterward. Stay tuned!

**Comment by moczka** [comment]
Im currently working on this merge and I am almost done. This module will do a lot more than just output the hours of each poll in a table. I realized since we are going to just display each early poll on the map. It will populate each "poll info card" with the hours, expand when the user clicks on the pointer of the poll on the map and since I am in charge of mapping the direction on desktop for the selected poll I will also add that functionality. On mobile the map will be hidden so instead it will provide you with a button to get the directions on the user's phone gps app.

**Comment by moczka** [comment]
screen shot 2016-10-19 at 9 36 29 pm

**Comment by moczka** [comment]
I merged the new_tabs branch in my fork with master and pushed it. You can try merging now. I have such poor internet connection where I am now. -_-

**Comment by moczka** [comment]
Alright guys, my module is all set. We really have to find a way of making the map google instance available at least in app.js because if we are to use the same map instance to display early polls and election day polls we need that. Thankfully, Lucy is working on refactoring the google maps.

**Comment by moczka** [comment]
![the way it looks on the first try]
When the page first loads.
(https://cloud.githubusercontent.com/assets/8846968/19568254/dba868c6-96be-11e6-8a7d-49d01520634c.png)

When you click on one of the poll info cards or a marker on the map.
on poll card expansion

**Comment by moczka** [comment]
solved conflicts. :)

**Comment by osesina** [comment]
Hi,
 
I am not getting this view (https://cloud.githubusercontent.com/assets/8846968/19568254/dba868c6-96be-11e6-8a7d-49d01520634c.png) when I build the current master... I'm trying to figure out where to jump in.

**Comment by moczka** [comment]
@osesina 

Hey Issac,

You won't be able to see it right now because it hasn't been merged from my branch onto master. If you want to get it to run on your computer. Create a remote to my fork. Follow these steps.

First, save and commit all your changes.

$ git branch poll-info-cards 
$ git branch checkout poll-info-cards
$ git remote add moczka-master https://github.com/moczka/cambridge_voting_locations.git
$ git fetch moczka-master
$ git pull moczka-master

Solve any conflicts if any and then run $ grunt server to view it. 
Don't forget to switch to the new branch "poll-info-cards" so you wont affect anything that you might be working on.

**Comment by moczka** [comment]
@osesina  It would be great if you could help us solve issue #57 I'm still trying to figure out a fix. You can also check out Lucy's pull request for the Map Refactoring and how we can implement that for both early polling and election day. Just some ideas.

**Pull request closed without merging**
